baseurl = "https://palazzetti.me/"
languageCode = "en-us"
title = "palazzetti.me"
theme = "beautifulhugo"
googleAnalytics = "UA-22634291-11"

[Params]
  gravatar = "f41ed5aca6a95f4c80b61850071ad557"
  subtitle = "Emanuele Palazzetti"

[Author]
  name = "Emanuele Palazzetti"
  email = "hello@palazzetti.me"
  github = "palazzem"
  twitter = "palazzem"
  linkedin = "in/palazzem"
